### ISSUE TITLE
RAM consumption Xvfd reaches almost 100% 

### ISSUE THREAD

**Issue by GildedHonour** [ponty/PyVirtualDisplay#21]
I have a script working on a server. Over time, as I can see in the dashboard of my server, the RAM consumption of Xvfd is increasing and reaching almost 100%. Here's my code:

```
from pyvirtualdisplay

display = Display(visible=0, size=(800, 600))
display.start()
# some staff

display.sendstop()
```
Am I releasing the Xvfd correctly?

**Comment by ponty** [comment]
I can not reproduce the problem.

Releasing is OK, stop() and sendstop() call subprocess.Popen.terminate.
(https://docs.python.org/3/library/subprocess.html#subprocess.Popen.terminate)

This may help:
http://blog.jeffterrace.com/2012/07/xvfb-memory-leak-workaround.html

**Comment by GildedHonour** [comment]
thanks.
