### ISSUE TITLE
Please release a new stable version.

### ISSUE THREAD

**Issue by leycec** [ponty/PyVirtualDisplay#37]
PyVirtualDisplay appears to have entered its senescent phase.

This is perfectly normal, of course. Even the most prolific software projects inevitably decline and dwindle into that good twilight world of historical obscurity.

## That is Not Dead Which Can Eternal Lie

In this case, however, PyVirtualDisplay *is* still widely used elsewhere – including as a mandatory dependency of [InstaPy](https://github.com/timgrossmann/InstaPy), [SeleniumBase](https://github.com/seleniumbase/SeleniumBase), and [pytest-xvfb](https://github.com/The-Compiler/pytest-xvfb). If PyVirtualDisplay summarily dies, all downstream packages either die as well *or* are required to significantly refactor their integration and support for X.

Neither of these two alternatives are ideal. In fact, both plainly suck.

## The Midnight Hour is Close at Hand

It's to the benefit of all involved that we keep PyVirtualDisplay alive as long as possible. The last stable release was [two-and-a-half years ago](https://github.com/ponty/PyVirtualDisplay/releases) and fails to explicitly support Python >= 3.6. That's... *not so good.*

If you no longer have the time or inclination to maintain PyVirtualDisplay, @ponty, that's perfectly understandable. In the interest of avoiding a community-driven fork, would granting repository push access to a proven community member (e.g., @Elias481) be feasible? If not, would temporarily resuscitating PyVirtualDisplay yourself for one final stable release be feasible?

## But Wait... There's More!

Sadly, releasing a new PyVirtualDisplay version is probably the least of the pending work that needs doing. Fun unpaid chores also include:

* Explicitly testing and supporting **Python 3.7.**
* Either merging *or* closing [all open pull requests](https://github.com/ponty/PyVirtualDisplay/pulls) – all of which seem fairly useful and constructive.
* At least commenting on [all open issues](https://github.com/ponty/PyVirtualDisplay/issues), some of which are over three years old. Ideally, issues that are *not* realistically resolvable should simply be closed.

## All that Begins Ends, Too

And... I'm done now.

Thanks for the many intrepid years of open-source volunteerism, @ponty. Whichever way you and PyVirtualDisplay elect to go, at least we'll always have version 0.2.1 and our shared memories of stabler, faster, and better supported days.

Pineapple express emoji for all! :pineapple: :train:

**Comment by ponty** [comment]
OK

**Comment by leycec** [comment]
**Caliente!** Well, *that* was both amazing and unexpected. 0-day turnaround on a moribund project is like open-source manna from Heaven.

Thanks for the inspiring revival, @ponty. You are a shining beacon of light to us all.
