### ISSUE TITLE
0.2.3 broken on Windows

### ISSUE THREAD

**Issue by surfaceowl** [ponty/PyVirtualDisplay#40]
PyVirtualDisplay is no longer working on Windows after [PR #35](https://github.com/ponty/PyVirtualDisplay/pull/35).  We do selenium testing in both Linux and Windows. Everything works great with PyVirtualDisplay v0.21, but fails with timeouts when we use v0.2.3.

 Per [the PyVirtualDisplay listing on pypi](https://pypi.org/project/PyVirtualDisplay/#history), it is an OS Independent library... so we need to change this useful check on the X Server so PyVirtualDisplay still words cross-platform.

[This PR added a check](https://github.com/ponty/PyVirtualDisplay/blame/5ae6aeb48be7618822b641568c3cbd455542cf9f/pyvirtualdisplay/abstractdisplay.py) to make sure the X Server used is solely used by PyVirtualDisplay to avoid a race condition.  This is a helpful change.  Unfortunately, the OS library used was `fcntl`, which is only available on Unix/Linux , and that **breaks cross-platform ability** of PyVirtualDisplay >0.2.1.  

**_Short term,_** in `abstractdisplay.py` we could change line 46 with functionality to only do this check if NOT on a windows machine.  
**current code:**  
```
if self.check_startup:
....do stuff
```
<br>

**Sample code:**
```
import platform
self.check_startup and platform.system() != "Windows":
....do stuff
else:
....pass
```

**_Long Term -_**  Could `fcntl` be replaced with a cross-platform library called`portalocker`?  This adds a python dependency but is fully cross-platform  Links on [pypi ](https://pypi.org/project/portalocker/)and [github](https://github.com/WoLpH/portalocker).  

I'm not familiar with the details of PyVirtualDisplay, but would be glad to help draft a fix and do regression testing on both Windows and Linux.

**Comment by ponty** [comment]
I didn't know this lib can be used on Windows.
What is the error message? ImportError?
In this case my solution would be:
https://github.com/benediktschmitt/py-filelock/blob/master/filelock.py#L47
```python
try:
    import fcntl
except ImportError:
    fcntl = None
```

**Comment by surfaceowl** [comment]
@ponty  --- yeah, we've been using this lib for about two years now.

The error message is ModuleNotFoundError- sorry didn't include earlier:
```
...\venv\lib\site-packages\pyvirtualdisplay\abstractdisplay.py", line 9, in <module> import fcntl
ModuleNotFoundError: No module named 'fcntl'
```

Agree the fix needs to be @import level, not around call to fcntl.

**Comment by ponty** [comment]
Can you please test 43aa3386beb6c667ab085d8a5d14b68b99b51c44 ?

**Comment by The-Compiler** [comment]
@ponty Maybe the check should be `if not fcntl and check_startup:` so the warning isn't logged when no check was requested anyways?

**Comment by ponty** [comment]
Fixed!

**Comment by The-Compiler** [comment]
Thanks @ponty, 0.2.4 seems to work fine for me! I guess this can be closed then?

**Comment by ponty** [comment]
OK, thanks
