### ISSUE TITLE
Is anyone else having problems with maximizing windows?

### ISSUE THREAD

**Issue by sfantu** [ponty/PyVirtualDisplay#43]

**Comment by The-Compiler** [comment]
What problems? How do you maximize a window? What window manager are you running? This doesn't seem related to PyVirtualDisplay FWIW.

**Comment by sfantu** [comment]
Hi ... i ain't using any wm. 
I managed to do it through xlib.

**Comment by ponty** [comment]
I don't understand the problem. Please provide more details.

**Comment by sfantu** [comment]
The "problem" was that my windows wouldn't maximize within pyvirtual display.
Reading more i realized that i needed a wm to maximize windows or do it as i found out through xlib.
You can close the issue
