### ISSUE TITLE
-resizeable option not on version of Xephyr bundled with xquartz 2.7.11

### ISSUE THREAD

**Issue by caccavale** [ponty/PyVirtualDisplay#44]
There are a couple options which don't exist for this version of xephyr/x/(etc) and break the library on MacOS Catalina.  Notably, `-resizeable` and `-displayfd`.  The latter is not an issue as long as `check_startup` is not passed to `Display(...)`. 

If you'd be willing to accept it I can PR a fix which allows `Display(..., resizeable=False)` and provides some better output for mac users (I kicked myself when I realized trying to debug with `check_startup` was the issue I was trying to debug).

**Comment by ponty** [comment]
It's OK, send a PR.

**Comment by ponty** [comment]
The `-resizeable` flag can be checked in the output of `Xephyr -help`.
