### ISSUE TITLE
Where can I find the changelog?

### ISSUE THREAD

**Issue by SuperSandro2000** [ponty/PyVirtualDisplay#60]
I am searching the changelog for 2.0 but I can't find it anywhere and 2.0 breaks builds (https://github.com/NixOS/nixpkgs/pull/109098) and I wondered why.

**Comment by The-Compiler** [comment]
I don't think there's a changelog, unfortunately. FWIW I'd also love to have one to know what changed between releases - the [git commit messages](https://github.com/ponty/PyVirtualDisplay/commits/master) usually aren't very helpful unfortunately :wink:

**Comment by ponty** [comment]
There is no changelog. The history can be checked in the git log, versions are tagged.
```
$ git log --oneline --decorate 1.3.2..2.0 | cut -c 9-| grep -v -e  test -e __version__ -e doc -e vagrant -e travis -e clean -e TODO -e init |sort
do not modify os.environ for xdpyinfo call
fix is_alive() and return_code before start()  #50
fix retries parameter
fix waitgrab(autocrop=False)
make is_started private #50
'manage_global_env' option for thread safe usage #57
py39 support
PYVIRTUALDISPLAY_DISPLAYFD env var
refactor start(): separate displayfd code from old code
refactor to autocrop() func
remove py2
remove pyscreenshot dependency
remove randomizer
setup.py: long_description_content_type
use pipes instead of temp files
```

Can you post the error message? I checked your link, but I couldn't find it.
I run also this command, but there is no error message:
```
nix-build -A python37Packages.virtual-display https://github.com/r-ryantm/nixpkgs/archive/4b7f9e6be5b5b551fe457be594d79052ac8bf641.tar.gz
```

**Comment by SuperSandro2000** [comment]
> Can you post the error message? I checked your link, but I couldn't find it.

Not sure why the bot failed to build most of the packages but on closer inspection they do build. Maybe the underlying issue already got fixed and was unrelated to this package.
