### ISSUE TITLE
Get X Display number

### ISSUE THREAD

**Issue by bigdav1178** [ponty/PyVirtualDisplay#61]
I would like to know how to determine the X Display number that is getting assigned by PyVirtualDisplay when set for Xvfb. I want to have ffmpeg record the xvfb display, but I'm not sure what input to give it. I tried running the "w" command from a console window, but it is only indicating the default :0 display.

**Comment by ponty** [comment]
```py
import os
from pyvirtualdisplay import Display

with Display() as disp:
    print(os.environ.get("DISPLAY"))

```
