### ISSUE TITLE
Running the Script involving pyvirtualdisplay Twice crashes the Colab

### ISSUE THREAD

**Issue by BluelyTASer** [ponty/PyVirtualDisplay#64]
https://user-images.githubusercontent.com/59511669/107593275-c024f200-6bed-11eb-9da6-8c294cd3c731.mp4

Google Colab's Black Screenshot of Death:
![monitor-1](https://user-images.githubusercontent.com/59511669/107593308-d5018580-6bed-11eb-8f7b-47a6a10568aa.png)

**Comment by ponty** [comment]
Please use text for reports: the program and the messages. I don't want to type in your program from the video.

Try first without mss. Is there any error then?

**Comment by BluelyTASer** [comment]
> Please use text for reports: the program and the messages. I don't want to type in your program from the video.
> 
> Try first without mss. Is there any error then?

```
from pyvirtualdisplay import Display
try:  
  disp = Display().start()
except Exception as e:
  disp.stop()
  print(e)
else:
  disp.stop()
  print("Ok!")
```

Seems like that is mss issue then, also ImageGrab for Screenshot example listed on README.md doesn't work on Linux because it requires windows or mac to do so. (ImportError: ImageGrab is macOS and Windows only)

https://user-images.githubusercontent.com/59511669/108596497-33540400-7364-11eb-816b-bac0c7c1d31a.mp4

Log Error Captured By Google Colab:
![482](https://user-images.githubusercontent.com/59511669/108596564-9ba2e580-7364-11eb-9493-c346b87c8bdf.PNG)

**Comment by ponty** [comment]
Check https://github.com/ponty/pyscreenshot/issues/79 

MSS was designed for X desktop and it reuses the display. It doesn't like if X is destroyed.
For screenshot I recommend Pillow. My lib `pyscreenshot` can also be used.

If you get this error message on Linux then your Pillow version is old.
```
ImportError: ImageGrab is macOS and Windows only
```
