### ISSUE TITLE
pyvirtualdisplay.abstractdisplay.XStartError: Xephyr program closed. command: ['Xephyr', '-br', '-screen', '1920x1080x24', '-displayfd', '6', '-resizeable'] stderr: b'No protocol specified\n\nXephyr cannot open host display. Is DISPLAY set?\n'

### ISSUE THREAD

**Issue by sudhirsilwal23** [ponty/PyVirtualDisplay#68]
pyvirtualdisplay version 2.2
Python version 3.6
Ubuntu 18.04
---------------------------------
I have already set the Display to 0 and executed export DISPLAY=:0 XAUTHORITY=/etc/X11/host-Xauthority.

**Comment by ponty** [comment]
Please make a short title, copy your program and the log in the message.
