### ISSUE TITLE
Clarify installation requirements on Windows/Mac

### ISSUE THREAD

**Issue by spookylukey** [ponty/PyVirtualDisplay#69]
It seems some people have got PyVirtualDisplay running on Windows (e.g. https://github.com/ponty/PyVirtualDisplay/issues/40 ) but other people are clearly saying this is not possible e.g. https://github.com/ponty/PyVirtualDisplay/issues/56

Could there be some clarification in the README about this, with some installation hints for the major platforms?

I'm guessing:
- for Windows you need to go the VNC route.  @surfaceowl could you contribute here?
- for Mac you need Xephyr

**Comment by ponty** [comment]
The installation requirement is to have the program installed you want to wrap: Xvfb, Xephyr or Xvnc.
I don't know how this can be done on Windows.
On Mac: `brew install --cask xquartz`
