### ISSUE TITLE
Hide Mouse Cursor in VirtualDisplay

### ISSUE THREAD

**Issue by gokulprathin8** [ponty/PyVirtualDisplay#70]
Is there a way to hide the cursor inside of Xvfb?

**Comment by ponty** [comment]
Can you show me a small program where the cursor is visible inside of Xvfb?
If you check the README you see that the cursor is not visible in my examples.

You can always pass extra parameters to Xvfb like 
```
extra_args=["-nocursor"]
```
Check `man xvfb` for possible parameters.

**Comment by michaelrampl** [comment]
Same Issue,

I'm using 
```
display  = Display(size=(rw, rh), visible=False, backend="xvfb", extra_args=["-nocursor"])
display.start()
displayEnvVar = os.environ.get("DISPLAY")
os.system("ffmpeg -f x11grab -video_size %dx%d -framerate 30 -i %s  -draw_mouse 0 Scenes/%s.mp4 &" % (rw, rh, displayEnvVar, fname))
```
In the recording, I'm seeing the cursor nevertheless

**Comment by ponty** [comment]
a3f430307634063f8cf43942d5fa950e8853570f
