### ISSUE TITLE
display.start() stacks on multiple session

### ISSUE THREAD

**Issue by lazarostso** [ponty/PyVirtualDisplay#74]
I am facing a big problem when i am trying to start virtual display in multiple sessions.
If multiple sessions try to start the display at the same time the script stacks there forever. No crash, no error, just it stacks there on every session. I need to stop some of them in order to unstack the others.
I tried to use a queue bit throught database in order to keep a priority for starting a display on each session but it didn't work properly. The problem still exists on multiple sessions. 
Does anyone have an idea?

**Comment by ponty** [comment]
Please provide more information. It is not clear how your use case can be reproduced.
