### ISSUE TITLE
GPU/Hardware Acceleration

### ISSUE THREAD

**Issue by michaelrampl** [ponty/PyVirtualDisplay#76]
Is there any way to enable GPU/Hardware Acceleration to run average applications smoothly?

**Comment by ponty** [comment]
How can you enable Hardware Acceleration with Xvfb?

**Comment by michaelrampl** [comment]
As far as I have seen there is no way for xvfb - but what about xnvc?

**Comment by ponty** [comment]
I don't know. Any idea?

**Comment by joellidin** [comment]
I would love to use hardware acceleration as well. How did you manage to do it?
