### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by chris-kehl** [ponty/PyVirtualDisplay#77]
Receiving this message:  ModuleNotFoundError: No module named 'pythonvirtualdisplay'

**Comment by The-Compiler** [comment]
Well, this project happens to be named "PyVirtualDisplay" and not "PythonVirtualDisplay" - same goes for the import, see [the README](https://github.com/ponty/PyVirtualDisplay#usage).

**Comment by ponty** [comment]
Try this:
```py
from pyvirtualdisplay import Display
```
